projects:
  lypsynconline-dev:
    schemaPath: graphql/schema.json
    includes:
      - graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: graphql
        region: eu-west-2
        apiId: jf5gtstj3vc35nqfy3m7mo2pmm
        maxDepth: 2
extensions:
  amplify:
    version: 3
